### ISSUE TITLE
Random SSL Error in Token v2

### ISSUE THREAD

**Issue by nekozgz** [bitdotioinc/python-bitdotio#29]
Using the v2 of the token, after instantiating the object using that token, it randomly displays the following error:

ERROR:
connection to server at "db.bit.io" (34.160.91.144), port 5432 failed: FATAL:  Unexpected Error
connection to server at "db.bit.io" (34.160.91.144), port 5432 failed: FATAL:  Must use SSL
DETAIL:  https://docs.bit.io/docs/connecting-via-ssl
HINT:  Add ?sslmode=require to your connection string

Is it a bit.io or python-bitdotio error? Can it be fixed?

**Comment by andrewdoss-bit** [comment]
Hi there, thanks for posting this issue and sorry to hear the connection isn't working for you. Unfortunately, I have been unable to reproduce this on my end but can look into this further if you are able to answer a few questions:

1. Are you still experiencing this issue when trying to connect?
2. Are you able to provide an example of the code you are using to make the connection (of course, with any credentials redacted)? We're also happy to investigate with you individually if you'd prefer to reach out at support@bit.io. 

In addition, `python-bitdotio` uses `psycopg2` which connects with `sslmode="prefer"` by default, while bit.io now requires SSL. That is causing the confusing SSL error message — `psycopg2` attempted to connect with SSL and failed due to a TBD `Unexpected Error`, which with `sslmode="prefer"` causes psycopg2 to retry the connection without SSL which then gets rejected, causing the trailing SSL error message. I'll get the `sslmode` updated to "require" so that the noisy SSL error messages go away.

**Comment by nekozgz** [comment]
Hi!

The indicated connection error appears randomly using the bit.io v2 token.

Maybe it's because you get an internal connection error over ssl and try without ssl.

The connection is made as follows, closing the connection when the instance ends.

```
self.connection_remote = bitdotio(self.cnx_remote).get_connection(self.SCHEMA)
self.cursor_remote = self.connection_remote.cursor(cursor_factory = RealDictCursor)
```

I will be happy to update the version as soon as they force sslmode to "required".

Keep me informed, thank you!

**Comment by andrewdoss-bit** [comment]
Thanks for the quick follow-up and connection example — I've bumped the package to v 2.0.0b with the sslmode = "required" change. As we both mention above, I don't think if will resolve the root connection issue you are experiencing, but it will remove the distracting SSL error messages. 

I will also try out your connection pattern and update you with what I find.

**Comment by andrewdoss-bit** [comment]
I'm sorry for the delay in follow-up on the connection pattern. I just tested out the latest release of `bitdotio` using the `RealDictCursor` and was unable to reproduce the `UnexpectedError`. 

One thing to double-check - is `self.SCHEMA` `Database` name shown when you retrieve credentials from bit.io? You likely have already seen that, but just in case, it has to have the form `<username>/<db_name>`. 

We've made a number of updates to the package in the last week, but if you are still encountering this issue please reach out at support@bit.io where we can provide more individualized troubleshooting!

**Comment by jmo-qap** [comment]
Closing this issue as stale, feel free to reopen @nekozgz if you're still having issues.

**Comment by jmo-qap** [comment]
Closing this issue as stale. Feel free to comment and I'll reopen if you're still having an issue @nekozgz
